### ISSUE TITLE
consumer_pool_size doesn't work

### ISSUE THREAD

**Issue by CyberGecko** [nttcom/fluent-plugin-rabbitmq#1]
Hi,

I just tried your fluent plugin and first of all it works like a charm.
But it seems the consumer_pool_size is not set correctly. When i configure the source like the following

```
<source>
  @type rabbitmq
  tag Log.TestApp
  host rabbit801.dus.via.de
  # or hosts ["192.168.1.1", "192.168.1.2"]
  vhost /
  queue Log_Queue
  heartbeat 10
  consumer_pool_size 5
  prefetch_count 1000
  durable true
  <parse>
    @type json
  </parse>
</source>
```

There is still only one consumer created.

I am not sure if there is a Problem with the configuration or the plugin.

**Comment by mmasaki** [comment]
Hi.

I tried the following code:

```ruby
require "bunny"

conn = Bunny.new
conn.start

ch = conn.create_channel(nil, 5) # set consumer_pool_size = 5
q = ch.queue("hoge")

q.subscribe do |_, _, payload|
  p payload
end

sleep
```

Then, I found there is the only one consumer.

```
% sudo rabbitmqctl list_consumers
Listing consumers ...
hoge    <rabbit@misc.3.25501.0> bunny-1497229806000-932144959461        false   0       []
```

It seems that bunny shares one consumer within threads in consumer pool and it's the intentional behavior of bunny.
