### ISSUE TITLE
Input : Include delivery_info data into fluentd message

### ISSUE THREAD

**Issue by meveno** [nttcom/fluent-plugin-rabbitmq#14]
Bunny offers to known which exchange and routing key were used for the incoming message (delivery_info.exchange and delivery_info.routing_key).
Would it be possible to add a flag (similar to the include_headers  flag) to add the possibility to include delivery_info ?
As fluentd is potentially used to collect multiple messages from various sources, it would be useful data to keep ...

**Comment by meveno** [comment]
Here is the corresponding PR : https://github.com/nttcom/fluent-plugin-rabbitmq/pull/15

**Comment by mmasaki** [comment]
Thank you for your PR. I merged it.
