### ISSUE TITLE
After installation service do not  work 

### ISSUE THREAD

**Issue by WoodProgrammer** [nttcom/fluent-plugin-rabbitmq#2]
I've already installed  fluent-plugin-rabbitmq but when i look the /var/log/td-agent/td-agent.log file I see that error log message . 

 [error]: config error file="/etc/td-agent/td-agent.conf" error="Unknown input plugin 'rabbitmq'. Run 'gem search -rd fluent-plugin' to find plugins"

**Comment by mmasaki** [comment]
Please use td-agent-gem command to install.
