### ISSUE TITLE
Option to use without creating new queue

### ISSUE THREAD

**Issue by vrastogi13** [nttcom/fluent-plugin-rabbitmq#3]
It seems this tries to create queue, we need a option to use existing queue. https://github.com/nttcom/fluent-plugin-rabbitmq/blob/master/lib/fluent/plugin/in_rabbitmq.rb#L106

**Comment by mmasaki** [comment]
The declaration will have no effect if the queue does already exist.

Please see: http://rubybunny.info/articles/queues.html
