### ISSUE TITLE
Getting error when using rabbitmq as an input for elasticsearch output

### ISSUE THREAD

**Issue by meskai** [nttcom/fluent-plugin-rabbitmq#6]
Hi, when i m using elastichsearch plugin for output, getting an error like this.
failed to emit error_class=NoMethodError error="undefined method `to_msgpack'

Can also check discussion here
[https://github.com/fluent/fluentd/issues/2072#issuecomment-408382144](url)

Configuration
---------------
```
<system>
  log_level info
  <log>
    time_format %Y-%m-%dT%H:%M:%S.%N%z
  </log>
</system>

<source>
  @type rabbitmq
  tag rabbitlog
  host 127.0.0.1
  user guest
  pass guest
  vhost /
  exchange app-logging
  queue log_que
  durable true
  routing_key rabbitlog
  heartbeat 10
  <parse>
    @type json
	time_key @timestamp
	keep_time_key false
  </parse>
</source>

#<match rabbitlog>
#  @type stdout
#</match>

<match rabbitlog>
  @type elasticsearch
  host localhost
  port 9200
  logstash_format true
</match>
```

fluentd-1.0.2 ruby="2.4.2"

plugins
----------

> 'fluent-plugin-elasticsearch' version '2.4.0'
> 'fluent-plugin-kafka' version '0.6.5'
> 'fluent-plugin-rabbitmq' version '0.0.3'
> 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
> 'fluent-plugin-s3' version '1.1.0'
> 'fluent-plugin-td' version '1.0.0'                                       
> 'fluent-plugin-td-monitoring' version '0.2.3'                            
> 'fluent-plugin-webhdfs' version '1.2.2'                                  
> 'fluent-plugin-windows-eventlog' version '0.2.2' 

Trace
------

> 2018-07-25T14:01:59.141706000+0300 [warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for 2018-07-25 17:01:56 +0300:Time" location="C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `write'" tag="rabbitlog"                                                                    
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `write'                                                                                                 
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `block in to_msgpack_stream'
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:107:in `each'
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:60:in `to_msgpack_stream'                                                                                     
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:890:in `block in <class:Output>'                                                                      
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:541:in `block in write_once'                                                                          
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'                                                                                                                       
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:532:in `write_once'                                                                                   
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:277:in `block in write'                                                                               
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:275:in `each'                                                                                         
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer.rb:275:in `write'                                                                                        
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:967:in `block in handle_stream_simple'
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:851:in `write_guard'                                                                                  
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:966:in `handle_stream_simple'                                                                         
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:841:in `execute_chunking'                                                                             
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:771:in `emit_buffered'                                                                                
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event_router.rb:96:in `emit_stream'                                                                                    
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event_router.rb:87:in `emit'                                                                                           
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rabbitmq-0.0.3/lib/fluent/plugin/in_rabbitmq.rb:118:in `block (2 levels) in start'                                                
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/parser_json.rb:64:in `parse'                                                                                    
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-rabbitmq-0.0.3/lib/fluent/plugin/in_rabbitmq.rb:116:in `block in start'                                                           
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer.rb:56:in `call'                                                                                                  
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/channel.rb:1717:in `block in handle_frameset'                                                                             
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:107:in `block (2 levels) in run_loop'                                                               
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:102:in `loop'                                                                                       
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:102:in `block in run_loop'                                                                          
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:101:in `catch'                                                                                      
> 2018-07-25T14:01:59.146708000+0300 [warn]: #0 C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/bunny-2.9.2/lib/bunny/consumer_work_pool.rb:101:in `run_loop'                                                                                 
> 2018-07-25T14:01:59.157705000+0300 [error]: #0 Uncaught exception from consumer 
> #<Bunny::Consumer:54245120 @channel_id=1 @queue=log_que> @consumer_tag=bunny-1532516459000-621352643544>: #<NoMethodError: undefined method `to_msgpack' for 2018-07-25 17:01:56 +0300:Time> @ 
> C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/event.rb:61:in `write'

**Comment by mmasaki** [comment]
Thank you for your report. It's fixed in 0.0.4.
